# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/focal64"

  config.vm.network "forwarded_port", guest: 1234, host: 2345

  config.vm.synced_folder "../", "/mapcomplete"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.provision :shell, privileged: false, path: "bootstrap.sh"
end
